### ISSUE TITLE
maybe I will make a content-free project

### ISSUE THREAD

**Issue by perondeidad** [eukara/freetfc#4]
Seeing how other projects are doing, such as Openarena, FreeDoom and LibreQuake. I think it would not be a bad idea to start a similar project with freeTFC. Maybe it's not Gabe or Carmack when it comes to programming or Coldest Poot or Cousin Gamers when it comes to coming up with something but I'll try and see if it works out. ¿opinions?

**Comment by eukara** [comment]
Absolutely, a content replacement would be wonderful.

**Comment by perondeidad** [comment]
I have news.
First: This is going to take a long time, it's my first time doing serious programming and I don't demo cubes simpler than table 1, it's going to take much longer than I thought and I'll have to go over C and Shell several times; modeling, mapping and figuring out how to compile without the engine crashing, Choosing manjaro as my main operating system, was not the best choice when it came down to it.

Second: Jolt can wait here for a few years, he just beats me, Jolt is in another league that I will arrive in 4-5 years (being optimistic).

Third: In my search to form a team for this, I found little or no initiative, especially from the communities (Latin America (Spanish-speaking, Luso-speaking and Franco-speaking) and Euskal herritarrak) of TF2, in one they expelled me thinking that I was a hacker or something I did, their only proof was a message taken out of context where there was a link to the FreeTFC Github page that said with the caption "here is the source code if you need it", I don't think they are all like that, I think not I have had the best of luck, I still have faith in this project

Something I want to clarify, I will be very busy from here until December (I will have more exams in the second half of the semester)
